// Generated by bilt-cloud from this project's database schema. Do not edit.
// Regenerated on every schema change; edits are overwritten.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

declare module '@biltme/backend' {
  interface Database {
    public: {
      Tables: {
        agent_settings: {
          Row: {
            id: string
            bakery_id: string
            enabled: boolean
            agent_name: string
            tone: string
            language: string
            greeting: string
            fallback_message: string
            handoff_keywords: string[]
            answer_only_from_knowledge: boolean
            auto_reply_outside_hours: boolean
            created_at: string
            updated_at: string
          }
          Insert: {
            id?: string
            bakery_id: string
            enabled?: boolean
            agent_name?: string
            tone?: string
            language?: string
            greeting?: string
            fallback_message?: string
            handoff_keywords?: string[]
            answer_only_from_knowledge?: boolean
            auto_reply_outside_hours?: boolean
            created_at?: string
            updated_at?: string
          }
          Update: {
            id?: string
            bakery_id?: string
            enabled?: boolean
            agent_name?: string
            tone?: string
            language?: string
            greeting?: string
            fallback_message?: string
            handoff_keywords?: string[]
            answer_only_from_knowledge?: boolean
            auto_reply_outside_hours?: boolean
            created_at?: string
            updated_at?: string
          }
          Relationships: [
            {
              foreignKeyName: 'agent_settings_bakery_id_fkey'
              columns: ['bakery_id']
              isOneToOne: false
              referencedRelation: 'bakeries'
              referencedColumns: ['id']
            },
          ]
        }
        bakeries: {
          Row: {
            id: string
            user_id: string
            name: string
            tagline: string | null
            about: string | null
            address: string | null
            city: string | null
            currency: string
            timezone: string
            order_lead_time: string | null
            opening_hours: Json
            created_at: string
            updated_at: string
          }
          Insert: {
            id?: string
            user_id: string
            name: string
            tagline?: string | null
            about?: string | null
            address?: string | null
            city?: string | null
            currency?: string
            timezone?: string
            order_lead_time?: string | null
            opening_hours?: Json
            created_at?: string
            updated_at?: string
          }
          Update: {
            id?: string
            user_id?: string
            name?: string
            tagline?: string | null
            about?: string | null
            address?: string | null
            city?: string | null
            currency?: string
            timezone?: string
            order_lead_time?: string | null
            opening_hours?: Json
            created_at?: string
            updated_at?: string
          }
          Relationships: []
        }
        conversations: {
          Row: {
            id: string
            bakery_id: string
            customer_name: string | null
            customer_phone: string
            status: string
            ai_paused: boolean
            is_test: boolean
            last_message_preview: string | null
            last_message_at: string
            unread_count: number
            created_at: string
            updated_at: string
          }
          Insert: {
            id?: string
            bakery_id: string
            customer_name?: string | null
            customer_phone: string
            status?: string
            ai_paused?: boolean
            is_test?: boolean
            last_message_preview?: string | null
            last_message_at?: string
            unread_count?: number
            created_at?: string
            updated_at?: string
          }
          Update: {
            id?: string
            bakery_id?: string
            customer_name?: string | null
            customer_phone?: string
            status?: string
            ai_paused?: boolean
            is_test?: boolean
            last_message_preview?: string | null
            last_message_at?: string
            unread_count?: number
            created_at?: string
            updated_at?: string
          }
          Relationships: [
            {
              foreignKeyName: 'conversations_bakery_id_fkey'
              columns: ['bakery_id']
              isOneToOne: false
              referencedRelation: 'bakeries'
              referencedColumns: ['id']
            },
          ]
        }
        delivery_zones: {
          Row: {
            id: string
            bakery_id: string
            area: string
            fee_cents: number
            min_order_cents: number
            eta: string | null
            notes: string | null
            sort_order: number
            created_at: string
            updated_at: string
          }
          Insert: {
            id?: string
            bakery_id: string
            area: string
            fee_cents?: number
            min_order_cents?: number
            eta?: string | null
            notes?: string | null
            sort_order?: number
            created_at?: string
            updated_at?: string
          }
          Update: {
            id?: string
            bakery_id?: string
            area?: string
            fee_cents?: number
            min_order_cents?: number
            eta?: string | null
            notes?: string | null
            sort_order?: number
            created_at?: string
            updated_at?: string
          }
          Relationships: [
            {
              foreignKeyName: 'delivery_zones_bakery_id_fkey'
              columns: ['bakery_id']
              isOneToOne: false
              referencedRelation: 'bakeries'
              referencedColumns: ['id']
            },
          ]
        }
        faqs: {
          Row: {
            id: string
            bakery_id: string
            question: string
            answer: string
            sort_order: number
            created_at: string
            updated_at: string
          }
          Insert: {
            id?: string
            bakery_id: string
            question: string
            answer: string
            sort_order?: number
            created_at?: string
            updated_at?: string
          }
          Update: {
            id?: string
            bakery_id?: string
            question?: string
            answer?: string
            sort_order?: number
            created_at?: string
            updated_at?: string
          }
          Relationships: [
            {
              foreignKeyName: 'faqs_bakery_id_fkey'
              columns: ['bakery_id']
              isOneToOne: false
              referencedRelation: 'bakeries'
              referencedColumns: ['id']
            },
          ]
        }
        messages: {
          Row: {
            id: string
            conversation_id: string
            role: string
            body: string
            handoff: boolean
            model: string | null
            created_at: string
          }
          Insert: {
            id?: string
            conversation_id: string
            role: string
            body: string
            handoff?: boolean
            model?: string | null
            created_at?: string
          }
          Update: {
            id?: string
            conversation_id?: string
            role?: string
            body?: string
            handoff?: boolean
            model?: string | null
            created_at?: string
          }
          Relationships: [
            {
              foreignKeyName: 'messages_conversation_id_fkey'
              columns: ['conversation_id']
              isOneToOne: false
              referencedRelation: 'conversations'
              referencedColumns: ['id']
            },
          ]
        }
        policies: {
          Row: {
            id: string
            bakery_id: string
            title: string
            body: string
            category: string
            sort_order: number
            created_at: string
            updated_at: string
          }
          Insert: {
            id?: string
            bakery_id: string
            title: string
            body: string
            category?: string
            sort_order?: number
            created_at?: string
            updated_at?: string
          }
          Update: {
            id?: string
            bakery_id?: string
            title?: string
            body?: string
            category?: string
            sort_order?: number
            created_at?: string
            updated_at?: string
          }
          Relationships: [
            {
              foreignKeyName: 'policies_bakery_id_fkey'
              columns: ['bakery_id']
              isOneToOne: false
              referencedRelation: 'bakeries'
              referencedColumns: ['id']
            },
          ]
        }
        products: {
          Row: {
            id: string
            bakery_id: string
            name: string
            description: string | null
            category: string
            price_cents: number
            unit: string | null
            available: boolean
            lead_time_hours: number | null
            allergens: string[]
            sort_order: number
            created_at: string
            updated_at: string
          }
          Insert: {
            id?: string
            bakery_id: string
            name: string
            description?: string | null
            category?: string
            price_cents?: number
            unit?: string | null
            available?: boolean
            lead_time_hours?: number | null
            allergens?: string[]
            sort_order?: number
            created_at?: string
            updated_at?: string
          }
          Update: {
            id?: string
            bakery_id?: string
            name?: string
            description?: string | null
            category?: string
            price_cents?: number
            unit?: string | null
            available?: boolean
            lead_time_hours?: number | null
            allergens?: string[]
            sort_order?: number
            created_at?: string
            updated_at?: string
          }
          Relationships: [
            {
              foreignKeyName: 'products_bakery_id_fkey'
              columns: ['bakery_id']
              isOneToOne: false
              referencedRelation: 'bakeries'
              referencedColumns: ['id']
            },
          ]
        }
        whatsapp_connections: {
          Row: {
            id: string
            bakery_id: string
            phone_number: string
            display_name: string | null
            status: string
            error_message: string | null
            connected_at: string | null
            created_at: string
            updated_at: string
            mode: string
            twilio_account_sid: string | null
            twilio_auth_token: string | null
            twilio_from_number: string | null
          }
          Insert: {
            id?: string
            bakery_id: string
            phone_number: string
            display_name?: string | null
            status?: string
            error_message?: string | null
            connected_at?: string | null
            created_at?: string
            updated_at?: string
            mode?: string
            twilio_account_sid?: string | null
            twilio_auth_token?: string | null
            twilio_from_number?: string | null
          }
          Update: {
            id?: string
            bakery_id?: string
            phone_number?: string
            display_name?: string | null
            status?: string
            error_message?: string | null
            connected_at?: string | null
            created_at?: string
            updated_at?: string
            mode?: string
            twilio_account_sid?: string | null
            twilio_auth_token?: string | null
            twilio_from_number?: string | null
          }
          Relationships: [
            {
              foreignKeyName: 'whatsapp_connections_bakery_id_fkey'
              columns: ['bakery_id']
              isOneToOne: false
              referencedRelation: 'bakeries'
              referencedColumns: ['id']
            },
          ]
        }
      }
      Views: {
        [name: string]: {
          Row: Record<string, any>
          Insert: Record<string, any>
          Update: Record<string, any>
          Relationships: []
        }
      }
      Functions: { [name: string]: { Args: Record<string, unknown>; Returns: any } }
      Enums: { [_ in never]: never }
      CompositeTypes: { [_ in never]: never }
    }
  }
}
